In [1]:
from keras.datasets import cifar10
from keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
#activation = use to apply activation function
#dropout = drops the unnecessary layer/neurons that are not in use
#conv2d = extract the features from images
import numpy as np
import matplotlib.pyplot as plt

In [2]:
(x_train,y_train),(x_test,y_test) = cifar10.load_data()

170498071/170498071 [==============================] - 3s 0us/step


In [3]:
x_train.shape

(50000, 32, 32, 3)

In [4]:
x_test.shape

(10000, 32, 32, 3)

In [5]:
x_train = x_train.astype("float32")
x_test = x_test.astype("float32")

In [6]:
x_train /= 255

In [7]:
x_test /= 255

In [8]:
from keras.models import Sequential
model = Sequential()

In [9]:
model.add(Conv2D(32,(3,3),padding="same",input_shape=x_train.shape[1:]))

In [10]:
model.add(Activation("relu"))

In [11]:
model.add(Conv2D(32,(3,3)))

In [12]:
model.add(Activation("relu"))

In [13]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [14]:
model.add(Dropout(0.25))

In [15]:
model.add(Flatten())

In [16]:
model.add(Dense(512))

In [17]:
model.add(Activation("relu"))

In [18]:
model.add(Dropout(0.5))

In [19]:
model.add(Dense(10))

In [20]:
model.add(Activation("softmax"))

In [21]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics='accuracy')

In [22]:
from keras.utils import to_categorical

y_train = to_categorical(y_train,10)
y_train[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

In [23]:
y_test = to_categorical(y_test,10)

In [24]:
model.fit(x_train,y_train,batch_size=32,epochs=5)

Epoch 1/5
1563/1563 [==============================] - 225s 143ms/step - loss: 1.3996 - accuracy: 0.4978
Epoch 2/5
1563/1563 [==============================] - 227s 145ms/step - loss: 1.0629 - accuracy: 0.6254
Epoch 3/5
1563/1563 [==============================] - 228s 146ms/step - loss: 0.9244 - accuracy: 0.6740
Epoch 4/5
1563/1563 [==============================] - 228s 146ms/step - loss: 0.8174 - accuracy: 0.7133
Epoch 5/5
1563/1563 [==============================] - 234s 150ms/step - loss: 0.7236 - accuracy: 0.7468


In [25]:
predictions=model.predict(x_test)
for i in range(5):
  print(y_test[i])
  print(predictions[i])

313/313 [==============================] - 10s 33ms/step
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[2.48528970e-03 8.09135454e-05 1.47110631e-03 8.16761255e-01
 2.68054020e-04 1.57112673e-01 2.43310351e-03 7.39459833e-03
 1.11471955e-02 8.45679257e-04]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[1.4489319e-03 8.1807572e-01 1.6654231e-09 1.6927793e-09 9.6404516e-11
 6.9381632e-13 1.6059086e-11 1.1349602e-12 1.8038304e-01 9.2322683e-05]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[2.6284304e-01 4.1531440e-02 1.1826679e-02 3.4303055e-03 6.4274454e-03
 8.0970458e-05 3.5654957e-05 1.2972063e-03 6.6729486e-01 5.2323574e-03]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[8.3781052e-01 2.7717124e-03 5.6144767e-03 6.3627325e-05 8.4725994e-04
 6.1480580e-07 4.7714584e-06 5.2762744e-07 1.5285631e-01 3.0209798e-05]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[9.22941672e-06 5.91390854e-05 2.40053274e-02 2.48804782e-02
 1.24737754e-01 9.47143591e-04 8.25304270e-01 1.84405253e-05
 3.65948981e-05 1.71130978e-06]
