In [1]:
import tensorflow as tf

In [2]:
#Create matrices of different shape using constant with the help of Tensorflow library
x = tf.constant([1,2,3,4,5,6],shape=[3,2])
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [3]:
tf.linalg.eigh(x)
#InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node SelfAdjointEigV2}}; Op<name=SelfAdjointEigV2; signature=input:T -> e:T, v:T; attr=compute_v:bool,default=true; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:SelfAdjointEigV2]

In [4]:
y = tf.constant([1,2,3,4,5,6],shape=[2,3])
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [5]:
#Create a 4*4 square matrix A with constant values from 1-16
x = tf.constant([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],shape=[4,4])
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])>

In [6]:
#Demonstrate matrix multiplication with the help of function of tensor flow library
x = tf.constant([1,2,3,4,5,6],shape=[3,2])
y = tf.constant([1,2,3,4,5,6],shape=[2,3])

z = tf.matmul(x,y)
z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

In [7]:
x = tf.constant([1,2,3,4,5,6],shape=[2,3])
y = tf.constant([7,8,9,10,11,12],shape=[3,2])

z = tf.matmul(x,y)
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [8]:
#With the help of tensorflow functions, create matrix using random values
a = tf.random.uniform([2,2], minval=3, maxval=10, dtype=tf.int32)
b = tf.random.uniform([3,3], minval=3, maxval=10, dtype=tf.float32)

In [9]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 3],
       [4, 6]])>

In [10]:
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[3.566772 , 8.384791 , 7.927113 ],
       [3.847481 , 7.6360598, 7.423953 ],
       [6.5550156, 3.8326516, 7.3747964]], dtype=float32)>

In [11]:
eigen_values,eigen_vectors = tf.linalg.eigh(b)

In [12]:
eigen_values

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-1.4413706,  4.1835938, 15.8354   ], dtype=float32)>

In [13]:
eigen_vectors

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.8199638 ,  0.23668848,  0.52118874],
       [-0.11039641, -0.8280255 ,  0.54971474],
       [-0.56166875,  0.50828373,  0.65282136]], dtype=float32)>