### Perform MultiCLass classification on the wine dataset using Feed Forward Neural Network.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
wine_data = load_wine()
x = wine_data.data
y = wine_data.target

In [ ]:
x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [ ]:
df = pd.DataFrame(wine_data.data, columns = wine_data.feature_names)
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [ ]:
df2 = pd.DataFrame(wine_data.target, columns = ["Target"])
df2.sample(10)

Target
133       2
72        1
41        0
26        0
80        1
88        1
53        0
79        1
61        1
126       1

In [ ]:
from keras.utils import np_utils
encoded_y = np_utils.to_categorical(df2)
encoded_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
model = Sequential()
model.add(Dense(8, input_dim=13, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [ ]:
#adam = mini batch gradient descent algo
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics="accuracy")

In [ ]:
model.fit(df, encoded_y, epochs=100, batch_size=10)

Epoch 1/100
18/18 [==============================] - 1s 3ms/step - loss: 51.8788 - accuracy: 0.4045
Epoch 2/100
18/18 [==============================] - 0s 3ms/step - loss: 26.7185 - accuracy: 0.4101
Epoch 3/100
18/18 [==============================] - 0s 2ms/step - loss: 4.1499 - accuracy: 0.5449
Epoch 4/100
18/18 [==============================] - 0s 2ms/step - loss: 1.6299 - accuracy: 0.5506
Epoch 5/100
18/18 [==============================] - 0s 2ms/step - loss: 1.0754 - accuracy: 0.5337
Epoch 6/100
18/18 [==============================] - 0s 2ms/step - loss: 0.8681 - accuracy: 0.6292
Epoch 7/100
18/18 [==============================] - 0s 2ms/step - loss: 0.8453 - accuracy: 0.6124
Epoch 8/100
18/18 [==============================] - 0s 2ms/step - loss: 0.8407 - accuracy: 0.6573
Epoch 9/100
18/18 [==============================] - 0s 2ms/step - loss: 0.8007 - accuracy: 0.7079
Epoch 10/100
18/18 [==============================] - 0s 2ms/step - loss: 0.7838 - accuracy: 0.6517
Epoch 1

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df,encoded_y,test_size=0.25,random_state=2)

In [ ]:
y_pred = model.predict(x_test)

y_pred

2/2 [==============================] - 0s 9ms/step


array([[9.99722004e-01, 1.33749767e-04, 1.44270831e-04],
       [9.71880317e-01, 2.65228301e-02, 1.59688387e-03],
       [1.28669599e-05, 3.19094211e-03, 9.96796250e-01],
       [3.94523405e-02, 9.41731155e-01, 1.88164078e-02],
       [7.38148689e-01, 2.40875423e-01, 2.09758021e-02],
       [9.97976899e-01, 1.80341571e-03, 2.19662237e-04],
       [1.68131173e-01, 8.01186979e-01, 3.06818075e-02],
       [1.64890043e-05, 6.29341183e-03, 9.93690073e-01],
       [1.37991458e-02, 8.74637127e-01, 1.11563675e-01],
       [9.56867278e-01, 3.10332924e-02, 1.20993387e-02],
       [7.30996728e-02, 9.23446715e-01, 3.45368055e-03],
       [9.99803305e-01, 1.08489323e-04, 8.83527318e-05],
       [9.99449849e-01, 4.08798165e-04, 1.41430006e-04],
       [3.88585395e-05, 6.10897643e-03, 9.93852198e-01],
       [6.62354068e-06, 9.33888648e-03, 9.90654528e-01],
       [1.14662995e-04, 9.56473231e-01, 4.34120856e-02],
       [9.89527524e-01, 9.81503911e-03, 6.57396042e-04],
       [9.95479763e-01, 3.61793

In [ ]:
def vec2scalar(list_):
    pred = []
    for i in list_:
        val = [round(j,0) for j in i]
        if val[0]==1.0:
            pred.append(0)
        elif val[1]==1.0:
            pred.append(1)
        else:
            pred.append(2)
    return pred


print(vec2scalar(y_pred))


[0, 0, 2, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 2, 2, 1, 0, 0, 0, 2, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 2, 1, 2, 2, 0, 1, 2, 1, 1, 1, 2, 2, 1, 0, 2]


In [ ]:
print(vec2scalar(y_test))

[0, 0, 2, 0, 0, 0, 1, 2, 1, 0, 1, 0, 0, 2, 2, 1, 0, 0, 0, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 0, 2, 1, 2, 2, 0, 1, 2, 1, 1, 1, 2, 2, 1, 0, 2]


In [ ]:
_, accuracy = model.evaluate(df, encoded_y)
print(f"Accuracy: {accuracy * 100:.2f}%")

6/6 [==============================] - 0s 4ms/step - loss: 0.2029 - accuracy: 0.9326
Accuracy: 93.26%
