### Solving XOR problem using Feed Forward Neural Network

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [2]:
model = Sequential()
model.add(Dense(units=2,activation='relu',input_dim=2))
model.add(Dense(units=1,activation='sigmoid'))

In [3]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')
print(model.summary())
print(model.get_weights())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None
[array([[ 1.0382453 , -0.52667195],
       [ 0.03058398,  0.22554088]], dtype=float32), array([0., 0.], dtype=float32), array([[0.45639777],
       [0.20641768]], dtype=float32), array([0.], dtype=float32)]


In [4]:
x = np.array([[0.,0,],[0.,1.],[1.,0.,],[1.,1.]])
print(x)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


In [5]:
y = np.array([0.,1.,1.,0.])
print(y)

[0. 1. 1. 0.]


In [6]:
model.fit(x,y,epochs=200,batch_size=4)

Epoch 1/200
1/1 [==============================] - 1s 1s/step - loss: 0.7018 - accuracy: 0.7500
Epoch 2/200
1/1 [==============================] - 0s 22ms/step - loss: 0.7016 - accuracy: 0.7500
Epoch 3/200
1/1 [==============================] - 0s 19ms/step - loss: 0.7013 - accuracy: 0.7500
Epoch 4/200
1/1 [==============================] - 0s 18ms/step - loss: 0.7011 - accuracy: 0.7500
Epoch 5/200
1/1 [==============================] - 0s 13ms/step - loss: 0.7009 - accuracy: 0.7500
Epoch 6/200
1/1 [==============================] - 0s 31ms/step - loss: 0.7007 - accuracy: 0.7500
Epoch 7/200
1/1 [==============================] - 0s 15ms/step - loss: 0.7005 - accuracy: 0.7500
Epoch 8/200
1/1 [==============================] - 0s 26ms/step - loss: 0.7003 - accuracy: 0.7500
Epoch 9/200
1/1 [==============================] - 0s 15ms/step - loss: 0.7000 - accuracy: 0.7500
Epoch 10/200
1/1 [==============================] - 0s 30ms/step - loss: 0.6998 - accuracy: 0.7500
Epoch 11/200
1/1 [===

In [7]:
print(model.get_weights())

[array([[ 0.9004589 , -0.52667195],
       [-0.18760708,  0.45549276]], dtype=float32), array([-0.09197982,  0.06593204], dtype=float32), array([[0.3692278],
       [0.4348492]], dtype=float32), array([-0.13801444], dtype=float32)]


In [8]:
predictions = model.predict(x)
predictions

1/1 [==============================] - 0s 397ms/step


array([[0.4726912 ],
       [0.52216715],
       [0.5400387 ],
       [0.5227914 ]], dtype=float32)

In [9]:
def prob_Bin(list_):
    pred = []
    for i in list_:
        if i>=0.5:
            pred.append(1)
        else:
            pred.append(0)
    return pred

In [10]:
prob_Bin(predictions)

[0, 1, 1, 1]

In [11]:
y

array([0., 1., 1., 0.])

In [12]:
_, accuracy = model.evaluate(x, y)
print(f"Accuracy: {accuracy * 100:.2f}%")

1/1 [==============================] - 1s 654ms/step - loss: 0.6614 - accuracy: 0.7500
Accuracy: 75.00%
